schedules:
- cron: "0 12 * * 0"
  displayName: "Weekly Renovate Check (Sun)"
  branches:
    include:
    - main
  always: true

trigger: none

pool:
  name: 'Plex Hosted Ubuntu 1604'

variables:
- group: 'GitHub API Token'

steps:
  - checkout: none

  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: '12.x'
      checkLatest: true

  - script: >
      npx renovate
      --platform "azure"
      --trust-level "high"
      --endpoint "$(System.CollectionUri)"
      --token "$(System.AccessToken)"
      --allowed-post-upgrade-commands "^node"
      $(System.TeamProject)/$(Build.Repository.Name)
    displayName: 'Run renovate'
    env:
      GITHUB_COM_TOKEN: $(github_token)
