require_relative '../../../common/temp/node_modules/.pnpm/node_modules/react-native/scripts/react_native_pods'
require_relative '../../../common/temp/node_modules/.pnpm/node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

pod 'OpenSSL-Universal', '~>1.0.2.20'

target 'Plant Floor - Prod' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
end

target 'Plant Floor - Dev' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
end

target 'Plant Floor - Test' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
end

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable these next few lines.
use_flipper!
post_install do |installer|
  flipper_post_install(installer)
end
